#ifndef KEYCODES_H
#define KEYCODES_H

#include <unordered_map>
#include <string>

// source: https://techdocs.altium.com/display/FPGA/PS2+Keyboard+Scan+Codes
// Define a mapping from scan code to key name
std::unordered_map<std::string, std::string> keycodes = {
    {"76", "ESC"},
    {"05", "F1"},
    {"06", "F2"},
    {"04", "F3"},
    {"0C", "F4"},
    {"03", "F5"},
    {"0B", "F6"},
    {"83", "F7"},
    {"0A", "F8"},
    {"01", "F9"},
    {"09", "F10"},
    {"78", "F11"},
    {"07", "F12"},
    // {"E07CE0F012", "Prt Scr"}, // release code: E0F07CE0F012
    {"7E", "Scroll Lock"},
    // {"E11477E1F014E077", "Pause/Break"}, // release code: None
    {"0E", "`"},
    {"16", "1"},
    {"1E", "2"},
    {"26", "3"},
    {"25", "4"},
    {"2E", "5"},
    {"36", "6"},
    {"3D", "7"},
    {"3E", "8"},
    {"46", "9"},
    {"45", "0"},
    {"4E", "-"},
    {"55", "="},
    {"66", "Backspace"},
    {"0D", "Tab"},
    {"15", "Q"},
    {"1D", "W"},
    {"24", "E"},
    {"2D", "R"},
    {"2C", "T"},
    {"35", "Y"},
    {"3C", "U"},
    {"43", "I"},
    {"44", "O"},
    {"4D", "P"},
    {"54", "["},
    {"5B", "]"},
    {"5D", "\\"},
    {"58", "Caps Lock"},
    {"1C", "A"},
    {"1B", "S"},
    {"23", "D"},
    {"2B", "F"},
    {"34", "G"},
    {"33", "H"},
    {"3B", "J"},
    {"42", "K"},
    {"4B", "L"},
    {"4C", ";"},
    {"52", "'"},
    {"5A", "Enter"},
    {"12", "Shift (left)"},
    {"1A", "Z"},
    {"22", "X"},
    {"21", "C"},
    {"2A", "V"},
    {"32", "B"},
    {"31", "N"},
    {"3A", "M"},
    {"41", ","},
    {"49", "."},
    {"4A", "/"},
    {"59", "Shift (right)"},
    {"14", "Ctrl (left)"},
    {"E01F", "Windows (left)"},
    {"11", "Alt (left)"},
    {"29", "Spacebar"},
    {"E011", "Alt (right)"},
    {"E027", "Windows (right)"},
    {"E02F", "Menus"},
    {"E014", "Ctrl (right)"},
    {"E070", "Insert"},
    {"E06C", "Home"},
    {"E07D", "Page Up"},
    {"E071", "Delete"},
    {"E069", "End"},
    {"E07A", "Page Down"},
    {"E075", "Up Arrow"},
    {"E06B", "Left Arrow"},
    {"E072", "Down Arrow"},
    {"E074", "Right Arrow"},
    {"77", "Num Lock"},
    {"E04A", "/"},
    {"7C", "Keypad *"},
    {"7B", "Keypad -"},
    {"6C", "Keypad 7"},
    {"75", "Keypad 8"},
    {"7D", "Keypad 9"},
    {"79", "Keypad +"},
    {"6B", "Keypad 4"},
    {"73", "Keypad 5"},
    {"74", "Keypad 6"},
    {"69", "Keypad 1"},
    {"72", "Keypad 2"},
    {"7A", "Keypad 3"},
    {"70", "Keypad 0"},
    {"71", "Keypad ."},
    {"E05A", "Enter"},
    {"F0", "Release"},
    {"E0", "Extended"} // some keys (e.g. arrows) use E0 tags
};

#endif // KEYCODES_H
