#ifndef NAMES_H
#define NAMES_H

/// The definitions of the key names. These appear on the display and the terminal.

#define PS2_ESC "ESC"
#define PS2_F1 "F1"
#define PS2_F2 "F2"
#define PS2_F3 "F3"
#define PS2_F4 "F4"
#define PS2_F5 "F5"
#define PS2_F6 "F6"
#define PS2_F7 "F7"
#define PS2_F8 "F8"
#define PS2_F9 "F9"
#define PS2_F10 "F10"
#define PS2_F11 "F11"
#define PS2_F12 "F12"
#define PS2_SCROLL_LOCK "Scroll Lock"
#define PS2_GRAVE "`"
#define PS2_1 "1"
#define PS2_2 "2"
#define PS2_3 "3"
#define PS2_4 "4"
#define PS2_5 "5"
#define PS2_6 "6"
#define PS2_7 "7"
#define PS2_8 "8"
#define PS2_9 "9"
#define PS2_0 "0"
#define PS2_MINUS "-"
#define PS2_EQUAL "="
#define PS2_BACKSPACE "Backspace"
#define PS2_TAB "Tab"
#define PS2_Q "Q"
#define PS2_W "W"
#define PS2_E "E"
#define PS2_R "R"
#define PS2_T "T"
#define PS2_Y "Y"
#define PS2_U "U"
#define PS2_I "I"
#define PS2_O "O"
#define PS2_P "P"
#define PS2_LEFT_BRACKET "["
#define PS2_RIGHT_BRACKET "]"
#define PS2_BACKSLASH "\\"
#define PS2_CAPS_LOCK "Caps Lock"
#define PS2_A "A"
#define PS2_S "S"
#define PS2_D "D"
#define PS2_F "F"
#define PS2_G "G"
#define PS2_H "H"
#define PS2_J "J"
#define PS2_K "K"
#define PS2_L "L"
#define PS2_SEMICOLON ";"
#define PS2_APOSTROPHE "'"
#define PS2_ENTER "Enter"
#define PS2_LEFT_SHIFT "Shift (left)"
#define PS2_Z "Z"
#define PS2_X "X"
#define PS2_C "C"
#define PS2_V "V"
#define PS2_B "B"
#define PS2_N "N"
#define PS2_M "M"
#define PS2_COMMA ","
#define PS2_DOT "."
#define PS2_SLASH "/"
#define PS2_RIGHT_SHIFT "Shift (right)"
#define PS2_LEFT_CTRL "Ctrl (left)"
#define PS2_LEFT_WINDOWS "Windows (left)"
#define PS2_LEFT_ALT "Alt (left)"
#define PS2_SPACEBAR "Spacebar"
#define PS2_RIGHT_ALT "Alt (right)"
#define PS2_RIGHT_WINDOWS "Windows (right)"
#define PS2_MENUS "Menus"
#define PS2_RIGHT_CTRL "Ctrl (right)"
#define PS2_INSERT "Insert"
#define PS2_HOME "Home"
#define PS2_PAGE_UP "Page Up"
#define PS2_DELETE "Delete"
#define PS2_END "End"
#define PS2_PAGE_DOWN "Page Down"
#define PS2_UP_ARROW "Up Arrow"
#define PS2_LEFT_ARROW "Left Arrow"
#define PS2_DOWN_ARROW "Down Arrow"
#define PS2_RIGHT_ARROW "Right Arrow"
#define PS2_NUM_LOCK "Num Lock"
#define PS2_KEYPAD_SLASH "Keypad /"
#define PS2_KEYPAD_ASTERISK "Keypad *"
#define PS2_KEYPAD_MINUS "Keypad -"
#define PS2_KEYPAD_7 "Keypad 7"
#define PS2_KEYPAD_8 "Keypad 8"
#define PS2_KEYPAD_9 "Keypad 9"
#define PS2_KEYPAD_PLUS "Keypad +"
#define PS2_KEYPAD_4 "Keypad 4"
#define PS2_KEYPAD_5 "Keypad 5"
#define PS2_KEYPAD_6 "Keypad 6"
#define PS2_KEYPAD_1 "Keypad 1"
#define PS2_KEYPAD_2 "Keypad 2"
#define PS2_KEYPAD_3 "Keypad 3"
#define PS2_KEYPAD_0 "Keypad 0"
#define PS2_KEYPAD_PERIOD "Keypad Period"
#define PS_KEYPAD_ENTER "Keypad enter"

#endif // NAMES_H