#ifndef USB_CODES_H
#define USB_CODES_H

#include <unordered_map>
#include <string>

// extra keycodes: https://www.win.tue.nl/~aeb/linux/kbd/scancodes-14.html
// some more: see usb_hid_keys.h
// note: as the code uses the arduino library by default, see: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardmodifiers/

std::unordered_map<std::string, uint8_t> usb_codes = {
    {"ESC", 0xB1},
    {"F1", 0xC2},
    {"F2", 0xC3},
    {"F3", 0xC4},
    {"F4", 0xC5},
    {"F5", 0xC6},
    {"F6", 0xC7},
    {"F7", 0xC8},
    {"F8", 0xC9},
    {"F9", 0xCA},
    {"F10", 0xCB},
    {"F11", 0xCC},
    {"F12", 0xCD},
    {"Scroll Lock", 0x47}, // ?
    {"`", '`'},
    {"1", '1'},
    {"2", '2'},
    {"3", '3'},
    {"4", '4'},
    {"5", '5'},
    {"6", '6'},
    {"7", '7'},
    {"8", '8'},
    {"9", '9'},
    {"0", '0'},
    {"-", '-'},
    {"=", '='},
    {"Backspace", 0xB2},
    {"Tab", 0xB3},
    {"Q", 'q'},
    {"W", 'w'},
    {"E", 'e'},
    {"R", 'r'},
    {"T", 't'},
    {"Y", 'y'},
    {"U", 'u'},
    {"I", 'i'},
    {"O", 'o'},
    {"P", 'p'},
    {"[", '['},
    {"]", ']'},
    {"\\", '\\'},
    {"Caps Lock", 0xC1},
    {"A", 'a'},
    {"S", 's'},
    {"D", 'd'},
    {"F", 'f'},
    {"G", 'g'},
    {"H", 'h'},
    {"J", 'j'},
    {"K", 'k'},
    {"L", 'l'},
    {";", ';'},
    {"\'", '\''},
    {"Enter", 0xB0},
    {"Shift (Left)", 0x81},
    {"Z", 'z'},
    {"X", 'x'},
    {"C", 'c'},
    {"V", 'v'},
    {"B", 'b'},
    {"N", 'n'},
    {"M", 'm'},
    {",", ','},
    {".", '.'},
    {"/", '/'},
    {"Shift (Right)", 0x85},
    {"Ctrl (left)", 0x80},
    {"Windows (left)", 0x83},
    {"Alt (left)", 0x82},
    {"Spacebar", ' '},
    {"Alt (right)", 0x86},
    {"Windows (right)", 0x87},
    //{"Menus", '?'},
    {"Ctrl (right)", 0x84},
    {"Insert", 0xD1},
    {"Home", 0xD2},
    {"Page Up", 0xD3},
    {"Delete", 0xD4},
    {"End", 0xD5},
    {"Page Down", 0xD6},
    {"Up Arrow", 0xDA},
    {"Left Arrow", 0xD8},
    {"Down Arrow", 0xD9},
    {"Right Arrow", 0xD7},
    //{"Num Lock", '?'},
    {"*", '*'},
    {"+", '+'},
};

#endif
